export const BOOTSTRAP_APP = "BOOTSTRAP_APP";
export const WEB3_NOT_SUPPORTED = "WEB3_NOT_SUPPORTED";
export const WEB3_SUPPORTED = "WEB3_SUPPORTED";
export const WRONG_NETWORK = "WRONG_NETWORK";
export const NETWORK_CHANGED = "NETWORK_CHANGED";
export const ACCOUNT_CHANGED = "ACCOUNT_CHANGED";
export const CONNECT_WALLET = "CONNECT_WALLET";
export const REQUEST_NETWROK_SWITCH = "REQUEST_NETWROK_SWITCH";
